const Countries = [
    "Pakistan",
    "Canada",
    "Czechia",
    "Guinea",
    "Cambodia",
    "South Georgia and the South Sandwich Islands",
    "Ukraine",
    "Mauritius",
    "Seychelles",
    "Afghanistan",
    "Barbados",
    "Northern Mariana Islands",
    "Svalbard and Jan Mayen",
    "India",
    "Cuba",
    "Myanmar",
    "Malta",
    "Syrian Arab Republic",
    "Georgia",
    "Djibouti",
    "Netherlands",
    "Sao Tome and Principe",
    "Oman",
    "Dominican Republic",
    "Puerto Rico",
    "Korea",
    "Tunisia",
    "Japan",
    "Kyrgyzstan",
    "Equatorial Guinea",
    "Malaysia",
    "Christmas Island",
    "Colombia",
    "Micronesia",
    "Kenya",
    "Republic of China",
    "Portugal",
    "Yemen",
    "Angola",
    "Faroe Islands",
    "Uzbekistan",
    "Belarus",
    "Libya",
    "Bahamas",
    "Kiribati",
    "Jamaica",
    "South Sudan",
    "Gibraltar",
    "Saint Kitts and Nevis",
    "Saint Martin",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Curaçao",
    "French Southern Territories",
    "Zambia",
    "Andorra",
    "Virgin Islands",
    "Guyana",
    "Lithuania",
    "Nicaragua",
    "Belize",
    "Iraq",
    "New Zealand",
    "Rwanda",
    "Liechtenstein",
    "Antarctica",
    "Antigua and Barbuda",
    "Malawi",
    "Germany",
    "South Africa",
    "Panama",
    "Palestine, State of",
    "Australia",
    "Martinique",
    "Benin",
    "Holy See",
    "French Guiana",
    "Côte d'Ivoire",
    "Nauru",
    "Congo",
    "Macedonia",
    "Philippines",
    "Cabo Verde",
    "Slovenia",
    "Sudan",
    "Serbia",
    "Tuvalu",
    "Egypt",
    "Luxembourg",
    "Macao",
    "Tonga",
    "Guernsey",
    "Niger",
    "Madagascar",
    "Montenegro",
    "Nigeria",
    "Tokelau",
    "Mauritania",
    "Paraguay",
    "Åland Islands",
    "Thailand",
    "Argentina",
    "Bermuda",
    "Samoa",
    "Bouvet Island",
    "Romania",
    "Mongolia",
    "French Polynesia",
    "Greenland",
    "Kazakhstan",
    "Tajikistan",
    "Maldives",
    "Lebanon",
    "Timor - Leste",
    "Poland",
    "American Samoa",
    "Singapore",
    "Swaziland",
    "Iceland",
    "Haiti",
    "Ghana",
    "Vanuatu",
    "Bulgaria",
    "British Indian Ocean Territory",
    "Marshall Islands",
    "Venezuela",
    "Nepal",
    "Zimbabwe",
    "Bangladesh",
    "Croatia",
    "Guinea - Bissau",
    "Cyprus",
    "Anguilla",
    "Honduras",
    "Algeria",
    "Italy",
    "Western Sahara",
    "Estonia",
    "Bosnia and Herzegovina",
    "Norway",
    "Slovakia",
    "Cocos Islands",
    "Isle of Man",
    "Brunei Darussalam",
    "Denmark",
    "Montserrat",
    "Spain",
    "Saudi Arabia",
    "Morocco",
    "Namibia",
    "Trinidad and Tobago",
    "Sint Maarten",
    "Guadeloupe",
    "Peru",
    "Norfolk Island",
    "Réunion",
    "Virgin Islands",
    "Ethiopia",
    "Cameroon",
    "Lao People's Democratic Republic",
    "Guatemala",
    "Latvia",
    "Jordan",
    "Saint Barthélemy",
    "Guam",
    "Hong Kong",
    "Comoros",
    "New Caledonia",
    "Sri Lanka",
    "Finland",
    "Saint Pierre and Miquelon",
    "Albania",
    "China",
    "Qatar",
    "Russian Federation",
    "Palau",
    "Cayman Islands",
    "Turkmenistan",
    "Sierra Leone",
    "Chile",
    "Sweden",
    "Wallis and Futuna",
    "Cook Islands",
    "Liberia",
    "Mayotte",
    "Saint Lucia",
    "Kuwait",
    "Botswana",
    "United States Minor Outlying Islands",
    "Fiji",
    "San Marino",
    "Burundi",
    "Bolivia",
    "Suriname",
    "Costa Rica",
    "Ireland",
    "El Salvador",
    "Tanzania, United Republic of",
    "Grenada",
    "Korea",
    "Uruguay",
    "Uganda",
    "Indonesia",
    "Turks and Caicos Islands",
    "Brazil",
    "Switzerland",
    "Mozambique",
    "Gabon",
    "Saint Vincent and the Grenadines",
    "Pitcairn",
    "Burkina Faso",
    "United Arab Emirates",
    "Heard Island and McDonald Islands",
    "Turkey",
    "Gambia",
    "Armenia",
    "France",
    "Solomon Islands",
    "Dominica",
    "Monaco",
    "Bhutan",
    "Congo",
    "Bonaire, Sint Eustatius and Saba",
    "Greece",
    "Bahrain",
    "Austria",
    "Senegal",
    "Falkland Islands",
    "Togo",
    "Aruba",
    "Moldova",
    "Chad",
    "United States of America",
    "Belgium",
    "Azerbaijan",
    "Viet Nam",
    "Niue",
    "Jersey",
    "Mexico",
    "Israel",
    "Lesotho",
    "Somalia",
    "Eritrea",
    "Papua New Guinea",
    "Hungary",
    "Iran",
    "United Kingdom of Great Britain and Northern Ireland",
    "Ecuador",
    "Mali",
    "Central African Republic",
]
export default Countries;